apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
        - name: reactapp
          image: tushar25l/devops-react-app:1.0
          ports:
            - containerPort: 80
